In [1]:
import numpy as np
import cvxpy as cp

In [2]:
total_value = 1650.0
n = 3

A = np.eye(n)
A[0,0] = 1/total_value
A[1,1] = 110/total_value
A[2,2] = 200/total_value

b = np.ones((n,))
b[0] = 0.0
b[1] = 0.45
b[2] = 0.55

#np.random.seed(0)
#m, n= 10, 10
#A = np.random.rand(m, n)
#b = np.random.randn(m)
x = cp.Variable(n, integer=True)

objective = cp.Minimize(cp.sum_squares(A @ x - b))
prob = cp.Problem(objective, [cp.sum(A @ x) == 1, x >= 0])
prob.solve()

0.006873278236914703

In [3]:
x.value.dtype

dtype('float64')

In [4]:
200/1650

0.12121212121212122

In [5]:
import pandas as pd

In [6]:
positions = pd.DataFrame({
    "symbol": ["cash", "VW","VV"], 
    "position": [100/total_value, 550/total_value, 1000/total_value], 
    "price": [1, 110, 200], 
    "shares": [100, 5, 5]}
)

In [7]:
positions["total"] = positions["price"] * positions["shares"]

In [8]:
positions.set_index("symbol", inplace=True)

In [9]:
for symbol, row in positions.iterrows():
    print(symbol, row.loc["shares"])

cash 100.0
VW 5.0
VV 5.0


In [10]:
from fin.env.simulator import TradingSimulator

In [11]:
simulator = TradingSimulator(positions)

In [12]:
simulator.total_value

1650

In [22]:
new_positions = positions.copy()

In [27]:
new_positions.loc["cash","position"] = 0.3
new_positions.loc["VW","position"] = 0.2
new_positions.loc["VV","position"] = 0.5

In [28]:
simulator.reposition(new_positions)

[[0.00060606 0.         0.        ]
 [0.         0.06666667 0.        ]
 [0.         0.         0.12121212]]
[0.3 0.2 0.5]
[520.   3.   4.]
cash 520.0
VW 3.0
VV 4.0


In [29]:
simulator.positions

position  price  shares  total
symbol                                
cash    0.315152      1     520    520
VW      0.200000    110       3    330
VV      0.484848    200       4    800

In [30]:
positions

position  price  shares  total
symbol                                
cash    0.060606      1     100    100
VW      0.333333    110       5    550
VV      0.606061    200       5   1000